<?php
$slug = isset($_GET['slug']) ? trim((string) $_GET['slug']) : 'demo-resto';
?>
<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>MiRestoApp · Carta Online</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
  <style>
    body { background: #f7f7fb; }
    .brand-header { background: linear-gradient(135deg, #e64389 0%, #e9bdd0 100%); color: #fff; }
    .sticky-cart { position: sticky; top: 20px; }
    .producto-card { border: 1px solid #ececf1; }
    .section-title { border-left: 4px solid #e64389; padding-left: 10px; }
  </style>
</head>
<body>
  <div class="container py-4">
    <div class="card brand-header mb-4"><div class="card-body d-flex justify-content-between align-items-center flex-wrap gap-2"><div><h2 class="mb-1" id="restoNombre">Cargando carta...</h2><small id="restoMeta"></small></div><div class="d-flex gap-2"><input id="buscador" class="form-control" placeholder="Buscar producto..." style="min-width:220px;"></div></div></div>
    <div class="row g-4"><div class="col-lg-8"><div id="menuContainer"></div></div><div class="col-lg-4"><div class="card sticky-cart"><div class="card-header"><strong>Carrito</strong></div><div class="card-body"><div id="carritoItems" class="small text-muted">Sin productos</div><hr><div class="d-flex justify-content-between"><span>Subtotal</span><strong id="cartSubtotal">$ 0.00</strong></div><div class="d-flex justify-content-between"><span>Envío</span><strong id="cartEnvio">$ 0.00</strong></div><div class="d-flex justify-content-between fs-5 mt-2"><span>Total</span><strong id="cartTotal">$ 0.00</strong></div></div><div class="card-footer"><button class="btn btn-primary w-100" data-bs-toggle="modal" data-bs-target="#checkoutModal">Finalizar pedido</button></div></div></div></div>
  </div>

  <div class="modal fade" id="checkoutModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Checkout</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><form id="checkoutForm" class="row g-3"><div class="col-md-6"><label class="form-label">Nombre</label><input class="form-control" name="nombre" required></div><div class="col-md-6"><label class="form-label">Teléfono</label><input class="form-control" name="telefono" required></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" name="email" type="email"></div><div class="col-md-6"><label class="form-label">Tipo</label><select class="form-select" name="tipo" id="checkoutTipo"><option value="delivery">Delivery</option><option value="retiro">Retiro en local</option></select></div><div class="col-12" id="direccionWrap"><label class="form-label">Dirección</label><input class="form-control" name="direccion"></div><div class="col-md-6" id="latWrap"><label class="form-label">Latitud (opcional)</label><input class="form-control" name="lat"></div><div class="col-md-6" id="lngWrap"><label class="form-label">Longitud (opcional)</label><input class="form-control" name="lng"></div><div class="col-md-6"><label class="form-label">Método de pago</label><select class="form-select" name="metodo_pago"><option value="contra_entrega">Pago contra entrega</option><option value="mercadopago">Mercado Pago</option></select></div><div class="col-md-6"><label class="form-label">Observaciones</label><input class="form-control" name="observaciones"></div></form><div id="checkoutMsg" class="mt-3 small"></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button><button type="button" class="btn btn-primary" id="btnConfirmarCheckout">Confirmar pedido</button></div></div></div></div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <script>
    const slug = <?php echo json_encode($slug, JSON_UNESCAPED_UNICODE); ?>;
    let menuData = null;
    let cart = JSON.parse(localStorage.getItem('mr_cart_' + slug) || '[]');
    function persist(){localStorage.setItem('mr_cart_'+slug,JSON.stringify(cart));}
    function money(v){return '$ '+Number(v||0).toFixed(2);}    
    function renderCart(){const box=carritoItems;const subtotal=cart.reduce((a,i)=>a+i.total,0),envio=0,total=subtotal+envio;box.innerHTML=!cart.length?'<span class="text-muted">Sin productos</span>':cart.map((i,x)=>`<div class="mb-2 border-bottom pb-2"><div class="d-flex justify-content-between"><strong>${i.nombre} x${i.cantidad}</strong><button class="btn btn-sm btn-link text-danger p-0" onclick="removeCartItem(${x})">Quitar</button></div><div>${i.detalle_texto||''}</div><div><strong>${money(i.total)}</strong></div></div>`).join('');cartSubtotal.textContent=money(subtotal);cartEnvio.textContent=money(envio);cartTotal.textContent=money(total);persist();}
    window.removeCartItem=(i)=>{cart.splice(i,1);renderCart();};
    function renderMenu(){if(!menuData)return;const q=buscador.value.trim().toLowerCase();menuContainer.innerHTML=menuData.categorias.map(cat=>{const ps=cat.productos.filter(p=>p.nombre.toLowerCase().includes(q)||(p.descripcion||'').toLowerCase().includes(q));if(!ps.length)return '';return `<div class="mb-4"><h4 class="section-title mb-3">${cat.nombre}</h4><div class="row g-3">${ps.map(prod=>`<div class="col-md-6"><div class="card producto-card h-100"><div class="card-body d-flex flex-column gap-2"><h5 class="mb-0">${prod.nombre}</h5><div class="text-muted small">${prod.descripcion||''}</div><div><strong>${money(prod.precio_base)}</strong></div>${prod.variantes.length?`<div><label class="form-label form-label-sm">Variante</label><select class="form-select form-select-sm" id="var_${prod.id}"><option value="">Sin variante</option>${prod.variantes.map(v=>`<option value="${v.id}" data-precio="${v.precio_adicional}">${v.nombre} (+${money(v.precio_adicional)})</option>`).join('')}</select></div>`:''}${prod.modificadores.length?`<div><label class="form-label form-label-sm">Modificadores</label><div class="small">${prod.modificadores.map(m=>`<label class="d-block"><input type="checkbox" class="mod_${prod.id}" value="${m.id}" data-precio="${m.precio_adicional}" data-nombre="${m.nombre}"> ${m.nombre} (+${money(m.precio_adicional)})</label>`).join('')}</div></div>`:''}<div class="mt-auto d-flex gap-2"><input type="number" min="1" value="1" class="form-control form-control-sm" id="qty_${prod.id}" style="max-width:90px;"><button class="btn btn-sm btn-primary" onclick="addToCart(${prod.id})">Agregar</button></div></div></div></div>`).join('')}</div></div>`;}).join('')||'<div class="alert alert-warning">No se encontraron productos.</div>';}
    window.addToCart=(id)=>{const p=menuData.categorias.flatMap(c=>c.productos).find(x=>x.id===id);if(!p)return;const qty=Number(document.getElementById('qty_'+id).value||1);if(qty<=0)return;let pu=Number(p.precio_base),vid=null;const det=[];const vs=document.getElementById('var_'+id);if(vs&&vs.value){const o=vs.options[vs.selectedIndex];vid=Number(vs.value);const plus=Number(o.dataset.precio||0);pu+=plus;det.push({nombre:o.textContent});}const mods=[];document.querySelectorAll('.mod_'+id+':checked').forEach(c=>{const plus=Number(c.dataset.precio||0);pu+=plus;mods.push(Number(c.value));det.push({nombre:c.dataset.nombre});});cart.push({producto_id:p.id,nombre:p.nombre,cantidad:qty,variante_id:vid,modificadores:mods,detalle_texto:det.map(d=>d.nombre).join(', '),precio_unitario:pu,total:pu*qty});renderCart();};
    async function cargarCarta(){const r=await fetch('app/api/mr/menu.php?slug='+encodeURIComponent(slug));const d=await r.json();if(!d.ok){menuContainer.innerHTML=`<div class="alert alert-danger">${d.error||'No se pudo cargar la carta.'}</div>`;return;}menuData=d;restoNombre.textContent=d.restaurante.nombre;restoMeta.textContent=d.restaurante.telefono||'';renderMenu();}
    async function checkout(){checkoutMsg.className='mt-3 small';if(!cart.length){checkoutMsg.classList.add('text-danger');checkoutMsg.textContent='El carrito está vacío.';return;}const fd=new FormData(checkoutForm),tipo=fd.get('tipo');const payload={slug,tipo,metodo_pago:fd.get('metodo_pago'),observaciones:fd.get('observaciones'),cliente:{nombre:fd.get('nombre'),telefono:fd.get('telefono'),email:fd.get('email')},direccion:tipo==='delivery'?{direccion:fd.get('direccion'),lat:fd.get('lat'),lng:fd.get('lng')}:{},items:cart.map(i=>({producto_id:i.producto_id,cantidad:i.cantidad,variante_id:i.variante_id,modificadores:i.modificadores}))};const r=await fetch('app/api/mr/checkout.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();if(!d.ok){checkoutMsg.classList.add('text-danger');checkoutMsg.textContent=d.error||'No se pudo generar el pedido.';return;}if(fd.get('metodo_pago')==='mercadopago'){const pr=await fetch('app/api/mr/payments/mercadopago_preference.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pedido_id:d.pedido_id})}),pd=await pr.json();if(!pd.ok){checkoutMsg.classList.add('text-danger');checkoutMsg.textContent=pd.error||'Pedido creado, pero no se pudo iniciar Mercado Pago.';return;}const url=pd.init_point||pd.sandbox_init_point;if(url){window.location.href=url;return;}}
      checkoutMsg.classList.add('text-success');checkoutMsg.textContent=`Pedido #${d.pedido_id} generado correctamente.`;cart=[];renderCart();checkoutForm.reset();}
    btnConfirmarCheckout.addEventListener('click',checkout);buscador.addEventListener('input',renderMenu);checkoutTipo.addEventListener('change',e=>{const d=e.target.value==='delivery';direccionWrap.style.display=d?'block':'none';latWrap.style.display=d?'block':'none';lngWrap.style.display=d?'block':'none';});
    renderCart();cargarCarta();
  </script>
</body>
</html>
