<?php
include('include-header.php');

$mrUser = mr_user();
$defaultRestauranteId = mr_resolve_restaurante_id($mrUser, 0);
?>
<body>
<div class="layout-wrapper layout-content-navbar"><div class="layout-container"><?php include('include-menu.php'); ?><div class="layout-page"><?php include('include-navbar.php'); ?><div class="content-wrapper"><div class="container-xxl flex-grow-1 container-p-y">
<div class="d-flex justify-content-between align-items-center mb-3"><h4>Pedido Telefónico</h4></div>
<div class="row g-3"><div class="col-lg-4"><div class="card"><div class="card-body"><h6>Cliente</h6><div class="input-group mb-2"><input id="telefonoBusqueda" class="form-control" placeholder="Teléfono"><button id="btnBuscarCliente" class="btn btn-primary">Buscar</button></div><input id="clienteNombre" class="form-control mb-2" placeholder="Nombre"><input id="clienteTelefono" class="form-control mb-2" placeholder="Teléfono"><input id="clienteEmail" class="form-control mb-2" placeholder="Email"><input id="clienteDireccion" class="form-control mb-2" placeholder="Dirección"><input id="clienteReferencia" class="form-control mb-2" placeholder="Referencia"><input id="clienteLat" class="form-control mb-2" placeholder="Latitud"><input id="clienteLng" class="form-control mb-2" placeholder="Longitud"><input id="zonaId" class="form-control mb-2" placeholder="Zona ID (opcional)"><select id="tipoPedido" class="form-select mb-2"><option value="telefono">Telefónico</option><option value="delivery">Delivery</option><option value="retiro">Retiro</option></select><select id="metodoPago" class="form-select mb-2"><option value="contra_entrega">Contra entrega</option><option value="mercadopago">Mercado Pago</option></select><textarea id="observaciones" class="form-control" placeholder="Observaciones"></textarea><hr><div id="historialCliente" class="small text-muted">Sin búsqueda.</div></div></div></div>
<div class="col-lg-8"><div class="card mb-3"><div class="card-body"><h6>Agregar ítems</h6><div class="row g-2"><div class="col-md-5"><select id="productoSelect" class="form-select"></select></div><div class="col-md-2"><input id="productoCantidad" type="number" min="1" value="1" class="form-control"></div><div class="col-md-3"><select id="varianteSelect" class="form-select"><option value="">Sin variante</option></select></div><div class="col-md-2 d-grid"><button id="btnAgregarItem" class="btn btn-primary">Agregar</button></div><div class="col-12" id="modsWrap"></div></div></div></div>
<div class="card"><div class="card-body"><table class="table" id="tablaItems"><thead><tr><th>Producto</th><th>Cant</th><th>Detalle</th><th>Subtotal</th><th></th></tr></thead><tbody></tbody></table><div class="d-flex justify-content-between"><strong>Total</strong><strong id="totalPedido">$ 0.00</strong></div><div class="mt-3 d-grid"><button id="btnCrearPedido" class="btn btn-success">Crear pedido</button></div><div id="msgEstado" class="mt-2 small"></div></div></div></div></div>
</div><?php include('include-footer.php'); ?><div class="content-backdrop fade"></div></div></div></div></div>
<?php include('include-js-import.php'); ?>
<script>
const userRole=<?php echo json_encode($rol ?? ''); ?>; const items=[]; let productos=[],variantesActuales=[],modificadoresActuales=[];
const defaultRestauranteId = Number(<?php echo json_encode((int) $defaultRestauranteId); ?> || 0);
function rest(){
	if(userRole!=='superadmin') return 0;
	const fromQuery = Number(new URLSearchParams(location.search).get('restaurante_id')||0);
	return fromQuery>0 ? fromQuery : defaultRestauranteId;
}
function withQ(u){const r=rest();if(r<=0)return u;return u+(u.includes('?')?'&':'?')+'restaurante_id='+r;} function money(v){return '$ '+Number(v||0).toFixed(2);}
async function cargarProductos(){const r=await fetch(withQ('api/mr/admin/productos.php'),{credentials:'same-origin'}),d=await r.json();if(!d.ok){alert(d.error||'Error productos');return;}productos=d.productos;productoSelect.innerHTML='<option value="">Seleccionar producto</option>';productos.forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=`${p.nombre} (${money(p.precio_base)})`;productoSelect.appendChild(o);});}
async function cargarVM(pid){if(!pid){variantesActuales=[];modificadoresActuales=[];varianteSelect.innerHTML='<option value="">Sin variante</option>';modsWrap.innerHTML='';return;}const [rv,rm]=await Promise.all([fetch('api/mr/admin/variantes.php?producto_id='+pid,{credentials:'same-origin'}),fetch('api/mr/admin/modificadores.php?producto_id='+pid,{credentials:'same-origin'})]);const dv=await rv.json(),dm=await rm.json();variantesActuales=dv.ok?dv.variantes:[];modificadoresActuales=dm.ok?dm.modificadores:[];varianteSelect.innerHTML='<option value="">Sin variante</option>';variantesActuales.forEach(v=>{const o=document.createElement('option');o.value=v.id;o.textContent=`${v.nombre} (+${money(v.precio_adicional)})`;varianteSelect.appendChild(o);});modsWrap.innerHTML=modificadoresActuales.map(m=>`<label class="me-3 small"><input type="checkbox" class="mod-check" value="${m.id}"> ${m.nombre} (+${money(m.precio_adicional)})</label>`).join('');}
function render(){const tb=document.querySelector('#tablaItems tbody');tb.innerHTML='';let total=0;items.forEach((it,i)=>{total+=it.subtotal;const tr=document.createElement('tr');tr.innerHTML=`<td>${it.nombre}</td><td>${it.cantidad}</td><td>${it.detalle||'-'}</td><td>${money(it.subtotal)}</td><td><button class="btn btn-sm btn-outline-danger" onclick="removeItem(${i})">Quitar</button></td>`;tb.appendChild(tr);});totalPedido.textContent=money(total);} window.removeItem=(i)=>{items.splice(i,1);render();};
productoSelect.addEventListener('change',e=>cargarVM(Number(e.target.value||0)));
btnAgregarItem.addEventListener('click',e=>{e.preventDefault();const pid=Number(productoSelect.value||0),cant=Number(productoCantidad.value||1),vid=Number(varianteSelect.value||0),mods=Array.from(document.querySelectorAll('.mod-check:checked')).map(x=>Number(x.value));if(!pid||cant<=0)return alert('Producto/cantidad inválidos');const p=productos.find(x=>Number(x.id)===pid);let precio=Number(p.precio_base),det=[];if(vid){const v=variantesActuales.find(x=>Number(x.id)===vid);if(v){precio+=Number(v.precio_adicional||0);det.push(v.nombre);}}mods.forEach(mid=>{const m=modificadoresActuales.find(x=>Number(x.id)===mid);if(m){precio+=Number(m.precio_adicional||0);det.push(m.nombre);}});items.push({producto_id:pid,nombre:p.nombre,cantidad:cant,variante_id:vid||null,modificadores:mods,detalle:det.join(', '),subtotal:precio*cant});render();});
btnBuscarCliente.addEventListener('click',async()=>{const t=telefonoBusqueda.value.trim();if(!t)return alert('Ingresá teléfono');const r=await fetch(withQ('api/mr/admin/cliente_telefono.php?telefono='+encodeURIComponent(t)),{credentials:'same-origin'}),d=await r.json();if(!d.ok)return alert(d.error||'Error');if(!d.cliente){historialCliente.textContent='Cliente nuevo, sin historial.';clienteTelefono.value=t;return;}clienteNombre.value=d.cliente.nombre||'';clienteTelefono.value=d.cliente.telefono||'';clienteEmail.value=d.cliente.email||'';if((d.direcciones||[]).length){clienteDireccion.value=d.direcciones[0].direccion||'';clienteReferencia.value=d.direcciones[0].referencia||'';clienteLat.value=d.direcciones[0].lat||'';clienteLng.value=d.direcciones[0].lng||'';}historialCliente.innerHTML=(d.historial||[]).length?d.historial.map(h=>`#${h.id} · ${h.estado} · ${money(h.total)} · ${h.created_at}`).join('<br>'):'Sin historial';});
btnCrearPedido.addEventListener('click',async()=>{msgEstado.className='mt-2 small';if(!items.length){msgEstado.classList.add('text-danger');msgEstado.textContent='Agregá al menos un item.';return;}const p={tipo:tipoPedido.value,metodo_pago:metodoPago.value,observaciones:observaciones.value,cliente:{nombre:clienteNombre.value,telefono:clienteTelefono.value,email:clienteEmail.value},direccion:{direccion:clienteDireccion.value,referencia:clienteReferencia.value,lat:clienteLat.value,lng:clienteLng.value},zona_id:Number(zonaId.value||0),items:items.map(i=>({producto_id:i.producto_id,cantidad:i.cantidad,variante_id:i.variante_id,modificadores:i.modificadores}))};if(userRole==='superadmin')p.restaurante_id=rest();const r=await fetch('api/mr/admin/pedido_manual.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}),d=await r.json();if(!d.ok){msgEstado.classList.add('text-danger');msgEstado.textContent=d.error||'No se pudo crear';return;}if(metodoPago.value==='mercadopago'){const pr=await fetch('api/mr/payments/mercadopago_preference.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({pedido_id:d.pedido_id})});const pd=await pr.json();if(pd.ok&&(pd.init_point||pd.sandbox_init_point)){window.open(pd.init_point||pd.sandbox_init_point,'_blank');}}
msgEstado.classList.add('text-success');msgEstado.textContent=`Pedido #${d.pedido_id} creado correctamente.`;items.length=0;render();});
cargarProductos();
</script>
</body></html>
