<?php
include('include-header.php');
?>
<body>
<div class="layout-wrapper layout-content-navbar"><div class="layout-container"><?php include('include-menu.php'); ?><div class="layout-page"><?php include('include-navbar.php'); ?><div class="content-wrapper"><div class="container-xxl flex-grow-1 container-p-y">
<div class="d-flex justify-content-between align-items-center mb-3"><h4>Zonas de envío</h4></div>
<div class="card mb-3"><div class="card-body"><form id="formZona" class="row g-2"><input type="hidden" id="zonaId"><div class="col-md-3"><input id="zonaNombre" class="form-control" placeholder="Nombre" required></div><div class="col-md-2"><input id="zonaCosto" type="number" min="0" step="0.01" class="form-control" placeholder="Costo envío" required></div><div class="col-md-2"><input id="zonaMinimo" type="number" min="0" step="0.01" class="form-control" placeholder="Pedido mínimo" required></div><div class="col-md-2"><select id="zonaTipo" class="form-select"><option value="manual">Manual</option><option value="radio">Radio</option><option value="poligono">Polígono</option></select></div><div class="col-md-1"><select id="zonaActiva" class="form-select"><option value="1">Activa</option><option value="0">Inactiva</option></select></div><div class="col-md-2 d-grid"><button class="btn btn-primary">Guardar</button></div><div class="col-md-3"><input id="zonaLat" class="form-control" placeholder="Centro lat"></div><div class="col-md-3"><input id="zonaLng" class="form-control" placeholder="Centro lng"></div><div class="col-md-3"><input id="zonaRadio" class="form-control" placeholder="Radio metros"></div><div class="col-md-12"><textarea id="zonaPoligono" class="form-control" rows="3" placeholder='Polígono JSON'></textarea></div></form></div></div>
<div class="card"><div class="card-body"><table class="table" id="tablaZ"><thead><tr><th>ID</th><th>Nombre</th><th>Tipo</th><th>Costo</th><th>Mínimo</th><th>Estado</th><th></th></tr></thead><tbody></tbody></table></div></div>
</div><?php include('include-footer.php'); ?><div class="content-backdrop fade"></div></div></div></div></div>
<?php include('include-js-import.php'); ?>
<script>
const userRole=<?php echo json_encode($rol ?? ''); ?>; function rest(){return userRole!=='superadmin'?0:Number(new URLSearchParams(location.search).get('restaurante_id')||0);} function q(){const r=rest();return r>0?('?restaurante_id='+r):'';}
async function load(){const r=await fetch('api/mr/admin/zonas.php'+q(),{credentials:'same-origin'}),d=await r.json();if(!d.ok){alert(d.error||'Error');return;}const tb=document.querySelector('#tablaZ tbody');tb.innerHTML='';d.zonas.forEach(z=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${z.id}</td><td>${z.nombre}</td><td>${z.tipo_area}</td><td>$ ${Number(z.costo_envio).toFixed(2)}</td><td>$ ${Number(z.pedido_minimo).toFixed(2)}</td><td>${z.activo?'Activa':'Inactiva'}</td><td><button class="btn btn-sm btn-outline-primary" onclick='ez(${JSON.stringify(z)})'>Editar</button></td>`;tb.appendChild(tr);});}
function ez(z){zonaId.value=z.id;zonaNombre.value=z.nombre;zonaCosto.value=z.costo_envio;zonaMinimo.value=z.pedido_minimo;zonaTipo.value=z.tipo_area||'manual';zonaActiva.value=z.activo?'1':'0';zonaLat.value=z.centro_lat??'';zonaLng.value=z.centro_lng??'';zonaRadio.value=z.radio_metros??'';zonaPoligono.value=z.poligono?JSON.stringify(z.poligono):'';} window.ez=ez;
formZona.addEventListener('submit',async(e)=>{e.preventDefault();let poly=null;const raw=zonaPoligono.value.trim();if(raw){try{poly=JSON.parse(raw);}catch(_){alert('JSON inválido');return;}}const id=Number(zonaId.value||0);const p={action:id?'update':'create',id,nombre:zonaNombre.value,costo_envio:Number(zonaCosto.value||0),pedido_minimo:Number(zonaMinimo.value||0),tipo_area:zonaTipo.value,activo:Number(zonaActiva.value)===1,centro_lat:zonaLat.value,centro_lng:zonaLng.value,radio_metros:zonaRadio.value,poligono:poly};if(userRole==='superadmin')p.restaurante_id=rest();const r=await fetch('api/mr/admin/zonas.php',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}),d=await r.json();if(!d.ok){alert(d.error||'Error');return;}e.target.reset();zonaId.value='';load();});
load();
</script>
</body></html>
